services:
  alma:
    build:
      context: .
      dockerfile: config/Dockerfile
    volumes:
      - ./db:/app/db
      - ./config/alma.env:/app/config/alma.env:ro
    environment:
      - ENVIRONMENT=production
    stdin_open: true
    tty: true
    restart: unless-stopped